### ISSUE TITLE
Dog Toy Visibility

### ISSUE THREAD

**Issue by relic-se** [Ian84Be/choose-your-own-adventure#1]
The game prompts that you can see the "TOY" before turning on your flashlight. You'll likely need to add some visibility toggle to the "TOY" object that starts at `False` until "USE" is performed on the flashlight in which it would be toggled to `True` and included in the "You can see" list.

![Screenshot from 2024-09-25 15-56-39](https://github.com/user-attachments/assets/18c4450a-a4ce-40d0-8b41-0bd8d4ac3750)
![Screenshot from 2024-09-25 15-57-03](https://github.com/user-attachments/assets/dfbf9f75-92d4-4d5b-a7f7-2d4186f1ff76)

**Comment by Ian84Be** [comment]
thanks for playing!
i just fixed this and a few other bugs in the last commit.
